name: CI

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ["1", "nightly"]
        julia-arch: ["default"]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        # We also run 1.0 and x86 tests, but only for Windows and Linux,
        # since mac's have a more complicated story with architectures.
        include:
          - julia-version: "1.0"
            julia-arch: default
            os: ubuntu-latest
          - julia-version: "1.0"
            julia-arch: default
            os: windows-latest
          - julia-version: "1"
            julia-arch: x86
            os: ubuntu-latest
          - julia-version: "1"
            julia-arch: x86
            os: windows-latest

    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - uses: julia-actions/cache@v3
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v3
        with:
          version: "lts"
      - run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - run: julia --project=docs --color=yes docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
